---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: do-token
  namespace: doks-cost-enforcer-system
spec:
  encryptedData:
    token: 
  template:
    metadata:
      name: do-token
      namespace: doks-cost-enforcer-system
