---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook
  namespace: doks-cost-enforcer-system
spec:
  encryptedData:
    url: 
  template:
    metadata:
      name: slack-webhook
      namespace: doks-cost-enforcer-system
